# Generated by Django 3.1.2 on 2020-10-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of product.', max_length=100)),
                ('description', models.TextField(help_text='Enter a description of product.', max_length=100)),
                ('price', models.PositiveIntegerField(help_text='Enter a price of product.')),
            ],
        ),
    ]
