# Generated by Django 3.1.2 on 2020-10-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='Enter a description of product.', max_length=200),
        ),
    ]
